### ISSUE TITLE
IllegalStateException if using inner test-classes and ValueProviderExtension been declared on top-level

### ISSUE THREAD

**Issue by yobinx** [TNG/value-provider#40]
Having inner classes inside the test and the ValueProviderExtension is been declared on the top-level class, e.g.:
```
@ExtendWith(ValueProviderExtension.class)
class MyTestClass {

    @Nested
    class MyInnerTestClass1 {
        @Test
        void test() {
        }
    }

    @Nested
    class MyInnerTestClass2 {
        @Test
        void test() {
        }
    }
}
```

Then the following exception is been thrown:

```
java.lang.IllegalStateException: Illegal transition, cannot switch from DEFAULT back to TEST_CLASS
	at com.google.common.base.Preconditions.checkState(Preconditions.java:836)
	at com.tngtech.valueprovider.ValueProviderFactory.checkMayFinish(ValueProviderFactory.java:90)
	at com.tngtech.valueprovider.ValueProviderFactory.doFinishTestClassCycle(ValueProviderFactory.java:62)
	at com.tngtech.valueprovider.ValueProviderFactory.finishTestClassCycle(ValueProviderFactory.java:152)
	at com.tngtech.valueprovider.ValueProviderExtension.finishTestClassCycle(ValueProviderExtension.java:115)
	at com.tngtech.valueprovider.ValueProviderExtension.afterAll(ValueProviderExtension.java:99)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by jonashoef** [comment]
Hello @yobinx again, 
according to my tests, support for `@Nested` test classes works by now on the branch `41-add-support-for-junit-5-lifecycle-per-class`. You are welcome to test yourself before a new version of the library is released. This would either give us the opportunity to fix remaining problems, or be more confident that our enhancements work as you expect.
